### ISSUE TITLE
ReferenceError: min is not defined

### ISSUE THREAD

**Issue by solbadguy2010** [Elethom/homebridge-gree-heatercooler-v2#10]
Hi, i get these errors and the Homebridge is restarting over and over until i disable your plugin:

[19/03/2021, 20:16:59] [homebridge-gree-heatercooler-v2] This plugin threw an error from the characteristic 'Cooling Threshold Temperature': Unhandled error thrown inside read handler for characteristic: min is not defined. See https://git.io/JtMGR for more info.
[19/03/2021, 20:16:59] [homebridge-gree-heatercooler-v2] This plugin threw an error from the characteristic 'Heating Threshold Temperature': Unhandled error thrown inside read handler for characteristic: min is not defined. See https://git.io/JtMGR for more info.

[19/03/2021, 20:17:02] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:07] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:12] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:17] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:22] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:27] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:32] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:37] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:42] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:47] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...

[19/03/2021, 20:17:52] [GreeAC] Device not found at 10.0.1.84:7000(f4911ed74c27), retrying...
[19/03/2021, 20:17:52] [GreeAC] Bound to device: f4911ed74c27
[19/03/2021, 20:17:54] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)

[19/03/2021, 20:17:54] Got SIGTERM, shutting down Homebridge...
[19/03/2021, 20:17:54] Got SIGTERM, shutting down child bridge process...

[19/03/2021, 20:17:55] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 20:17:56] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 20:17:57] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 20:17:58] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 20:17:59] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[19/03/2021, 20:18:04] [HB Supervisor] Restarting Homebridge...
[19/03/2021, 20:18:04] [HB Supervisor] Starting Homebridge with extra flags: -I

**Comment by solbadguy2010** [comment]
When i move your Plugin to a child bridge i get this over and over:

[19/03/2021, 20:25:54] [GreeAC] Child bridge process ended
[19/03/2021, 20:25:54] [GreeAC] Process Ended. Code: 1, Signal: null
[19/03/2021, 20:26:01] [GreeAC] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[19/03/2021, 20:26:02] [GreeAC] Launched child bridge with PID 5520
[19/03/2021, 20:26:02] Registering accessory 'homebridge-gree-heatercooler-v2.GreeHeaterCooler'
[19/03/2021, 20:26:02] [GreeAC] Loaded homebridge-gree-heatercooler-v2 v0.4.1 child bridge successfully
[19/03/2021, 20:26:02] [GreeAC] Config loaded: {
  "accessory": "GreeHeaterCooler",
  "address": "10.0.1.84",
  "mac": "f4911ed74c27",
  "model": "GWH24QD",
  "name": "GreeAC",
  "serialNumber": "4M33600000330",
  "minimumTargetTemperature": 16,
  "maximumTargetTemperature": 25,
  "fakeSensor": true,
  "sensorOffset": 0,
  "updateInterval": 1000,
  "retryInterval": 5000
}
Preparing Advertiser for 'GreeAC 0F64' using ciao backend!
Starting to advertise 'GreeAC 0F64' using ciao backend!
[19/03/2021, 20:26:02] Homebridge v1.3.4 (GreeAC) is running on port 47913.
[19/03/2021, 20:26:03] [GreeAC] Bound to device: f4911ed74c27

/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249
    return min(this.device.status[commands.targetTemperature.code] + 0.5 * (this.device.status[commands.temperatureOffset.code] - 1) + magicNumber, this.config.maximumTargetTemperature);
    ^
ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 20:26:04] [GreeAC] Child bridge process ended
[19/03/2021, 20:26:04] [GreeAC] Process Ended. Code: 1, Signal: null

**Comment by Elethom** [comment]
I'm terribly sorry for the issue. Should be fixed in 0.4.2.

**Comment by solbadguy2010** [comment]
No need to be sorry, you offer this for free.
It works again, thank you very much!
