### ISSUE TITLE
Socket is already bound

### ISSUE THREAD

**Issue by solbadguy2010** [Elethom/homebridge-gree-heatercooler-v2#3]
Hi,
i keep getting this error when i restart Homebridge without rebooting the Pi. Sadly not every time. It is not simply reproducable.

[14/01/2021, 09:37:43] [GreeAC] Error [ERR_SOCKET_ALREADY_BOUND]: Socket is already bound
    at Socket.bind (dgram.js:211:11)
    at Device._connect (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:31:19)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:43:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ERR_SOCKET_ALREADY_BOUND'
}

**Comment by solbadguy2010** [comment]
When i reboot the Pi it is working again.

**Comment by Elethom** [comment]
The only way for it to happen is everything went right except your AC didn't respond. I'll fix the retry mechanism but I strongly recommend you to check what's blocking the communications when you restart Homebridge. Make sure you use `hb-service`.

**Comment by Artoria2e5** [comment]
Do `lsof` for the occupied port. Or just `killall node`.

**Comment by solbadguy2010** [comment]
I use a standard image from homebridge.io. hb-service is used as is. 
Is it possible to integrade the suggested lsof in the loading process of the plugin? It could clear its own way.

**Comment by Elethom** [comment]
Resolved in 4e0f577.
